// Generated by CoffeeScript 1.4.0
(function() {

    define(["jquery"], function($) {
      var Toggle;
      return Toggle = (function() {
  
        function Toggle(context, toggle, toggler, togglable, callback) {
          var _this = this;
          this.context = context;
          this.callback = callback;
          this.$context = $(context);
          this.$toggle = this.$context.find(toggle);
          this.$toggler = this.$context.find(toggler);
          this.$togglable = this.$context.find(togglable);
          this.$toggler.on("click", function(event) {
            return _this.doToggle(_this.$togglable);
          });
        }
  
        Toggle.prototype.doToggle = function(togglable) {
          return togglable.slideToggle(250, function() {
            if (this.callback && typeof this.callback === "function") {
              return this.callback();
            }
          });
        };
  
        return Toggle;
  
      })();
    });
  
  }).call(this);
